matrix:
  include:
  - stage: Tox
    language: python
    python:
    - "3.6"
    install: pip install tox-travis
    script: tox

  - stage: Cypress
    language: node_js
    node_js:
    - 10
    python:
    - "3.6"
    install:
      - pip install -r req.text --user
      - cd src/main/vue
      - npm ci
    script:
      - python ../../main/python/server/site.py &
      - npm run dev &
      - npm test

